### ISSUE TITLE
Installation of blackfire extension fails

### ISSUE THREAD

**Issue by holtkamp** [cloudControl/buildpack-php#26] opened 2015-05-19 22:03 UTC
When trying to [install Blackfire using composer](https://github.com/cloudControl/buildpack-php#extensions), the result is not very sunny for this black magic extension :cry:

```
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 321 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
       
-----> Receiving push
-----> Packaging ext/blackfire 0.23.1 (for Zend module API version 20100525)...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 !     cloudControl push rejected, failed to compile php app
 !     
remote: error: hook declined to update refs/heads/test
To ssh://applicationName@cloudcontrolled.com/repository.git
 ! [remote rejected] deploymentName -> deploymentName (hook declined)
error: failed to push some refs to 'ssh://applicationName@cloudcontrolled.com/repository.git'
Command '['/usr/bin/git', 'push', u'ssh://applicationName@cloudcontrolled.com/repository.git', 'deploymentName']' returned non-zero exit status 1
```

Maybe [this is related?](http://stackoverflow.com/questions/29339420/curl-tar-gzip-stdin-not-in-gzip-format)

**Comment by pst** [comment] 2015-05-20 06:47
I can confirm the problem, however I don't think it's a problem with the code in the buildpack. It rather seems to be a problem with the downloaded file.

https://github.com/cloudControl/buildpack-php/blob/master/bin/util/blackfire.sh#L10

If I follow the download and extract steps there manually it seems it's supposed to be a tar.gz file but still `tar -xzf probe.tar.gz` complains.

```
$ curl -A "cloudControl" -o probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/${PHP_MAJOR_VERSION:=5}${PHP_MINOR_VERSION:=4} | grep 'X-Blackfire-Release-Version: ' | sed "s%X-Blackfire-Release-Version: %%" | sed s%.$%%
0.23.1
$ tar -zxf probe.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

@Nicofuma can you shed some light on this?

**Comment by Nicofuma** [comment] 2015-05-20 07:44
First, thanks for testing Blackfire :)
I'm looking into that but it seems to be due to a change in our architecture. Should be fixed soon I hope and I will get back  to you then.

**Comment by Nicofuma** [comment] 2015-05-20 13:48
It should be fixed now

**Comment by pst** [comment] 2015-05-20 18:04
Yes, my testing shows it is. I'll close the issue. @holtkamp please re-open if it still doesn't work for you.

**Comment by holtkamp** [comment] 2015-05-21 19:25
thanks, great work guys!

**Comment by holtkamp** [comment] 2015-11-17 13:54
It has been a while, but gave it another shot:
- got a working CloudControl deployment
- add ```"ext-blackfire": "*"``` to the ```composer.json``` in my deployments root folder
- commit changes
- push changes: ```cctrlapp projectName/deploymentName push```

This results in:

```
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 328 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
       
-----> Receiving push
Installing blackfire ...
-----> Packaging ext/blackfire 1.6.0 (for Zend module API version 20100525)...
     Done.
-----> Packaging bin/blackfire-agent 1.4.0...
     Done.
-----> Found php version definition ~5.6
-----> Using php version php-5.6.15
mkdir: cannot create directory `bin': File exists
 !     cloudControl push rejected, failed to compile custom app
 !     
-----> Custom buildpack provided
remote: error: hook declined to update refs/heads/deploymentName
To ssh://projectName@cloudcontrolled.com/repository.git
 ! [remote rejected] deploymentName -> deploymentName (hook declined)
error: failed to push some refs to 'ssh://projectName@cloudcontrolled.com/repository.git'
Command '['/usr/bin/git', 'push', u'ssh://projectName@cloudcontrolled.com/repository.git', 'deploymentName']' returned non-zero exit status 1
```

Do you guys monitor these kind of errors? Blackfire.io is gaining quite some traction, I can not imagine I am the only one trying to install this... Or is my deployment so exotic?

PS, it seems I can not re-open the issue?

**Comment by sfriesel** [comment] 2015-11-17 16:22
We'll look into this

**Comment by TooAngel** [comment] 2015-11-18 15:08
The problem was introduced with the latest changes on the buildpack. The error should be fixed by now.

**Comment by holtkamp** [comment] 2015-11-18 15:59
Thanks for the swift responses. 

I had a look, the installation seems to succeed, however PHP does generate a warning about loading the dynamic library during startup, see the end of the following trace:

```
cctrlapp projectName/deploymentName push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 328 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
       
-----> Receiving push
Installing blackfire ...
-----> Packaging ext/blackfire 1.6.0 (for Zend module API version 20100525)...
     Done.
-----> Packaging bin/blackfire-agent 1.4.0...
     Done.
-----> Found php version definition ~5.6
-----> Using php version php-5.6.15
-----> Loading extension: apcu
-----> Loading extension: bcmath
-----> Loading extension: blackfire
-----> Loading extension: bz2
-----> Loading extension: calendar
-----> Loading extension: curl
-----> Loading extension: dba
-----> Loading extension: gd
-----> Loading extension: gettext
-----> Loading extension: imagick
-----> Loading extension: intl
-----> Loading extension: mbstring
-----> Loading extension: mcrypt
-----> Loading extension: mongo
-----> Loading extension: mysql
-----> Loading extension: mysqli
-----> Loading extension: mysqlnd
-----> Loading extension: newrelic
-----> Loading extension: oauth
-----> Loading extension: pdo
-----> Loading extension: pdo_mysql
-----> Loading extension: soap
-----> Loading extension: sockets
-----> Loading extension: sysvmsg
-----> Loading extension: sysvsem
-----> Loading extension: sysvshm
-----> Loading extension: xmlrpc
-----> Loading extension: xsl
-----> Loading extension: zip
-----> Loading extension: zlib
-----> Installing composer dependencies...
PHP Warning:  PHP Startup: Unable to load dynamic library '/srv/www/php-5.6.15/lib/php/extensions/blackfire.so' - /srv/www/php-5.6.15/lib/php/extensions/blackfire.so: cannot open shared object file: No such file or directory in Unknown on line 0
```


When actually deploying and inspecting the ```phpinfo()``` output, nothing about BlackFire is listed..

**Closed** 2015-11-19 15:54 UTC

**Comment by TooAngel** [comment] 2015-11-19 17:42
Thank you for the hint. The blackfire addon integration was not yet prepared for php-5.5 and php-5.6. This is fixed now and we will include it in our automated tests to make sure that these problems can be prevented. Sorry for any inconveniences.

**Comment by holtkamp** [comment] 2015-11-20 09:12
Confirmed, both push and deploy now function correctly and the output of ```phpinfo()``` indicate that the Blackfire.io extension is installed properly, thanks!
